### ISSUE TITLE
Diseño de secciones del Portal de Cursos

### ISSUE THREAD

**Issue by aaramirez** [synergyvision/templategenerator#11]
- [ ] Definir la estructura de cada plantilla, secciones y componentes considerando los modelos de portales de cursos en línea usuales.

**Comment by stephanie-cruz** [comment]
Se proponen las siguientes secciones:

- [ ] Home

- [ ] Login / Signup

- [ ] Categorias

- [ ] Perfil de usuario

- [ ] Cursos

- [ ] Mis cursos

- [ ] Carrito
