### ISSUE TITLE
Diseño de las secciones del Portal Corporativo y Componentes

### ISSUE THREAD

**Issue by aaramirez** [synergyvision/templategenerator#2]
- [ ] Definir la estructura de cada plantilla, secciones y componentes considerando los modelos de portales Corporativos usuales.

**Comment by stephanie-cruz** [comment]
Se plantean secciones para el portal corporativo:

- [ ✅ ]  Sección de "Nuestros servicios"

- [ ✅ ]  Sección de "Contáctanos"

- [ ✅ ] Sección de "Nuestro equipo"

- [ ✅ ] Sección de redes sociales

- [ ] Sección "Sobre nosotros/Nuestra visión/ Propósito"

- [ ] Sección "Aliados"

- [ 👷🏻‍♀️ ]  Sección de Blog

- [ ✅ ] Sección de preguntas frecuentes . Se incluirá en la pagina de cada servicio

**Comment by stephanie-cruz** [comment]
Se plantean los siguientes componentes:

- [✅] Header

- [✅] Footer

- [✅]  Carrousel adaptable a cualquier tipo de cartas

- [✅]  Cartas de "Nuestros servicios"

- [✅] Formulario de contacto
