### ISSUE TITLE
Desarrollo de Componentes Web

### ISSUE THREAD

**Issue by aaramirez** [synergyvision/templategenerator#3]
- [ ] Crear los componentes de la plantilla Corporativa que van en _include y que permiten mostrar distintos tipos de información.

**Comment by stephanie-cruz** [comment]
Se plantean los siguientes componentes:

- [✅] Header

- [✅] Footer

- [✅]  Cartas de "Nuestros servicios"

- [✅] Cartas del equipo

- [ ] Formulario de contacto

- [✅] Componentes de botón primario, secundario y terciario

- [✅] Caja de _features_ del equipo

- [✅] Border

- [✅] Carta de publicación en blog

- [✅] Carta de pregunta

** Se crean componentes para diferentes secciones

Generales:

- [✅]  Carrousel adaptable a cualquier tipo de cartas

- [✅] Barras de progreso

- [✅ ] svg
