### ISSUE TITLE
Datos de la Plantilla

### ISSUE THREAD

**Issue by aaramirez** [synergyvision/templategenerator#5]
- [ ] Crear los datos de la plantilla Corporativa en _data. La idea es que las plantillas cambien y se modifiquen cambiando parámetros en _data. Todos los parámetros se deben manejar desde _data y evitar cablear, rutas de imágenes y textos. Estas deben ser parámetros.

**Comment by stephanie-cruz** [comment]
Se crean archivos yml dentro del directorio _data:

- global.yml
      * directorios y datos globales de la plantillas
- colors.yml
       * Colores primarios y secundarios de la plantilla
- footer.yml
- header.yml
** Se crea un archivo yaml por cada sección de la plantilla
