### ISSUE TITLE
Desarrollar las páginas de la plantilla

### ISSUE THREAD

**Issue by aaramirez** [synergyvision/templategenerator#7]
- [ ] Desarrollar las páginas de la plantilla Corporativa en base a la estructura definida y aprobada. Utilizar los parámetros en _data, componentes en _include y layouts en _layouts con sus estilos respectivos.

**Comment by stephanie-cruz** [comment]
- [x] Home

- [x] Team

- [x] Servicio

- [ ] Aliados

- [ ] Nosotros

- [x] Preguntas frecuentes

- [x] 404
